version: '3.1'
services:
  oracle-db:
    image: container-registry.oracle.com/database/enterprise:latest
    environment:
      ORACLE_SID: ORCLCDB
      ORACLE_PDB: ORCLPDB1
      ORACLE_PWD: YourPassword
    ports:
      - 1521:1521   
      - 5500:5500   
    volumes:
      - oracle-data:/opt/oracle/oradata   
    shm_size: '1g'  
volumes:
  oracle-data: